# Generated by Django 3.0.5 on 2020-04-21 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberNo', models.CharField(default='', max_length=100)),
                ('FirstName', models.CharField(default='', max_length=100)),
                ('LastName', models.CharField(default='', max_length=100)),
                ('MobileNo', models.CharField(default='', max_length=100)),
                ('IdNumber', models.CharField(default='', max_length=100)),
                ('Email', models.CharField(default='', max_length=100)),
                ('MemberType', models.CharField(choices=[('1', 'Member'), ('2', 'Chairperson'), ('3', 'Vice Chairperson'), ('4', 'Treasurer'), ('5', 'Assistant Treasurer'), ('6', 'Secretary'), ('7', 'Assistant Secretary'), ('8', 'Organizing Secretary'), ('9', 'Time Keeper')], default='1', max_length=20)),
                ('MemberGender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=20)),
                ('Password', models.CharField(default='', max_length=100)),
                ('NextOfKinFullName', models.CharField(default='', max_length=100)),
                ('NextOfKinFullMobileNo', models.CharField(default='', max_length=100)),
                ('NextOfKinRelationship', models.CharField(default='', max_length=100)),
                ('LastLogin', models.DateField(default=datetime.datetime.now)),
                ('CreatedDate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SettingKey', models.CharField(default='', max_length=100)),
                ('SettingName', models.CharField(default='', max_length=100)),
                ('SettingValue', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('Sender', models.CharField(default='', max_length=100)),
                ('Content', models.CharField(default='', max_length=255)),
                ('TicketRead', models.BooleanField(default=False)),
                ('CreatedDate', models.DateField(default=datetime.datetime.now)),
                ('ReadDate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=100)),
                ('LastName', models.CharField(default='', max_length=100)),
                ('Email', models.CharField(default='', max_length=100)),
                ('Password', models.CharField(default='', max_length=100)),
                ('IdNumber', models.CharField(default='', max_length=100)),
                ('MobileNo', models.CharField(default='', max_length=100)),
                ('LastLogin', models.DateField(default=datetime.datetime.now)),
                ('CreatedDate', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=100)),
                ('MobileNo', models.CharField(default='', max_length=100)),
                ('IdNumber', models.CharField(default='', max_length=100)),
                ('Salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('PendingLoans', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('MemberNo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sacco.Member')),
            ],
        ),
    ]
