# Generated by Django 3.0.5 on 2020-04-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='NextOfKinFullMobileNo',
            new_name='NextOfKinMobileNo',
        ),
    ]
