# Generated by Django 3.0.5 on 2020-04-25 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0002_auto_20200425_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='LastLogin',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
