# Generated by Django 3.0.5 on 2020-04-26 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0003_auto_20200425_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 20, 7, 13, 601748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='LastLogin',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 20, 7, 13, 601748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 20, 7, 13, 677552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ReadDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 20, 7, 13, 677552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 20, 7, 13, 678552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='LastLogin',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 20, 7, 13, 678552, tzinfo=utc)),
        ),
    ]
