# Generated by Django 3.0.5 on 2020-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0004_auto_20200426_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='CreatedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='LastLogin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='CreatedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ReadDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='CreatedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='LastLogin',
            field=models.DateTimeField(),
        ),
    ]
