# Generated by Django 3.0.5 on 2020-04-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0005_auto_20200426_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='LastLogin',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
