# Generated by Django 3.0.5 on 2020-04-26 21:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0006_auto_20200426_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='CreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 21, 8, 50, 134372, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='LastLogin',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 21, 8, 50, 134372, tzinfo=utc)),
        ),
    ]
