# Generated by Django 3.0.5 on 2020-04-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0008_auto_20200427_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial',
            name='Salary',
        ),
    ]
